-- Aggregate versions are generated by the student owner, not broker arrival order.
ALTER TABLE reporting.dim_student ADD COLUMN aggregate_version bigint NOT NULL DEFAULT 0;
ALTER TABLE reporting.dim_student ADD COLUMN source_occurred_at timestamptz;
ALTER TABLE reporting.dim_student ADD COLUMN source_event_id text;
ALTER TABLE reporting.dim_student ADD CONSTRAINT dim_student_aggregate_version_nonnegative CHECK (aggregate_version >= 0);
