-- Connected fee configuration: lifecycle, installments, optional heads and automatic concessions.
-- Existing bands remain published so current student assignments continue to work.

ALTER TABLE fee.fee_bands
    ADD COLUMN IF NOT EXISTS status VARCHAR(24) NOT NULL DEFAULT 'PUBLISHED',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS grace_period_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS late_fee_type VARCHAR(24) NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS late_fee_amount BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS late_fee_interval_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS supersedes_band_id VARCHAR(255) REFERENCES fee.fee_bands(id) ON DELETE SET NULL;

UPDATE fee.fee_bands
SET published_at = COALESCE(published_at, updated_at, created_at, now())
WHERE status = 'PUBLISHED';

ALTER TABLE fee.fee_bands
    DROP CONSTRAINT IF EXISTS chk_fee_band_status,
    ADD CONSTRAINT chk_fee_band_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    DROP CONSTRAINT IF EXISTS chk_fee_band_revision,
    ADD CONSTRAINT chk_fee_band_revision CHECK (revision > 0),
    DROP CONSTRAINT IF EXISTS chk_fee_band_grace_period,
    ADD CONSTRAINT chk_fee_band_grace_period CHECK (grace_period_days >= 0),
    DROP CONSTRAINT IF EXISTS chk_fee_band_late_fee,
    ADD CONSTRAINT chk_fee_band_late_fee CHECK (
        late_fee_type IN ('NONE', 'FIXED', 'DAILY')
        AND late_fee_amount >= 0
        AND late_fee_interval_days >= 0
    );

ALTER TABLE fee.fee_items
    ADD COLUMN IF NOT EXISTS optional BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_fee_band_supersedes
    ON fee.fee_bands (school_id, supersedes_band_id);

CREATE TABLE IF NOT EXISTS fee.fee_installments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT NOT NULL,
    band_id     VARCHAR(255) NOT NULL REFERENCES fee.fee_bands(id) ON DELETE CASCADE,
    label       VARCHAR(80) NOT NULL,
    due_date    DATE NOT NULL,
    share_percent NUMERIC(5,2) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_fee_installment_label UNIQUE (band_id, label),
    CONSTRAINT chk_fee_installment_share CHECK (share_percent > 0 AND share_percent <= 100)
);

CREATE INDEX IF NOT EXISTS idx_fee_installments_school_band
    ON fee.fee_installments (school_id, band_id, sort_order);

CREATE TABLE IF NOT EXISTS fee.fee_discount_rules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id        BIGINT NOT NULL,
    academic_year_id VARCHAR(255) NOT NULL,
    name             VARCHAR(120) NOT NULL,
    rule_type        VARCHAR(32) NOT NULL,
    percentage       NUMERIC(5,2) NOT NULL,
    priority         INTEGER NOT NULL DEFAULT 100,
    active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_fee_discount_rule_name UNIQUE (school_id, academic_year_id, name),
    CONSTRAINT chk_fee_discount_rule_type CHECK (
        rule_type IN ('SIBLING', 'STAFF_WARD', 'EARLY_PAYMENT', 'RTE', 'MERIT', 'MANUAL')
    ),
    CONSTRAINT chk_fee_discount_percentage CHECK (percentage >= 0 AND percentage <= 100)
);

ALTER TABLE fee.fee_assignments
    ADD COLUMN IF NOT EXISTS discount_rule_id BIGINT REFERENCES fee.fee_discount_rules(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS rule_discount NUMERIC(5,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gross_fee BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS selected_optional_item_ids_csv TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS base_payable BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS late_fee_accrued BIGINT NOT NULL DEFAULT 0;

UPDATE fee.fee_assignments
SET gross_fee = COALESCE((
        SELECT SUM(item.amount) FROM fee.fee_items item WHERE item.band_id = fee_assignments.band_id
    ), 0)
WHERE gross_fee = 0;

UPDATE fee.fee_assignments
SET base_payable = net_payable
WHERE base_payable = 0 AND net_payable > 0;

ALTER TABLE fee.fee_assignments
    DROP CONSTRAINT IF EXISTS chk_fee_assignment_rule_discount,
    ADD CONSTRAINT chk_fee_assignment_rule_discount CHECK (rule_discount >= 0 AND rule_discount <= 100),
    DROP CONSTRAINT IF EXISTS chk_fee_assignment_payable_components,
    ADD CONSTRAINT chk_fee_assignment_payable_components CHECK (
        gross_fee >= 0 AND base_payable >= 0 AND late_fee_accrued >= 0
    );

CREATE INDEX IF NOT EXISTS idx_fee_discount_rules_school_year
    ON fee.fee_discount_rules (school_id, academic_year_id, active, priority);

CREATE INDEX IF NOT EXISTS idx_fee_assignments_discount_rule
    ON fee.fee_assignments (school_id, discount_rule_id);

ALTER TABLE fee.fee_installments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fee.fee_installments;
CREATE POLICY tenant_isolation ON fee.fee_installments
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on');

ALTER TABLE fee.fee_discount_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fee.fee_discount_rules;
CREATE POLICY tenant_isolation ON fee.fee_discount_rules
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on');

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app_rt') THEN
  GRANT SELECT, INSERT, UPDATE, DELETE ON fee.fee_installments, fee.fee_discount_rules TO app_rt;
  GRANT USAGE, SELECT ON SEQUENCE fee.fee_installments_id_seq, fee.fee_discount_rules_id_seq TO app_rt;
END IF; END $$;
