substitutions:
  _REGION: asia-south2
  _AR_REPO: custoking
  _BACKEND_SERVICE: custoking-backend
  _FRONTEND_SERVICE: custoking-frontend
  _BACKEND_IMAGE: custoking-backend
  _FRONTEND_IMAGE: custoking-frontend
  _COMMIT_SHA: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_BACKEND_IMAGE}:${_COMMIT_SHA}', './backend']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_FRONTEND_IMAGE}:${_COMMIT_SHA}', './frontend']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_BACKEND_IMAGE}:${_COMMIT_SHA}']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_FRONTEND_IMAGE}:${_COMMIT_SHA}']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image=asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_BACKEND_IMAGE}:${_COMMIT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=SPRING_PROFILES_ACTIVE=prod,SPRING_DATASOURCE_URL=jdbc:postgresql://10.116.0.3:5432/custoking_ims_v1,SPRING_DATASOURCE_USERNAME=ims_app,APP_BOOTSTRAP_USERS=true,APP_CORS_ALLOWED_ORIGINS=https://custoking-frontend-755376288593.asia-south2.run.app,FLYWAY_URL=jdbc:postgresql://10.116.0.3:5432/custoking_ims_v1,FLYWAY_USERNAME=appuser
      - --set-secrets=SPRING_DATASOURCE_PASSWORD=ims-app-password:latest,APP_AADHAR_SECRET=aadhar-secret:latest,FLYWAY_PASSWORD=db-password:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_FRONTEND_SERVICE}
      - --image=asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_FRONTEND_IMAGE}:${_COMMIT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=80

images:
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_BACKEND_IMAGE}:${_COMMIT_SHA}'
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_FRONTEND_IMAGE}:${_COMMIT_SHA}'
