CREATE TABLE firefighting.outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key      VARCHAR(255) NOT NULL,
    event_type     VARCHAR(120) NOT NULL,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    school_id      BIGINT,
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    payload        JSONB        NOT NULL,
    published_at   TIMESTAMPTZ,
    attempts       INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_ff_outbox_unpublished ON firefighting.outbox_events (id) WHERE published_at IS NULL;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app_rt') THEN
  GRANT SELECT, INSERT, UPDATE, DELETE ON firefighting.outbox_events TO app_rt;
  GRANT USAGE, SELECT ON SEQUENCE firefighting.outbox_events_id_seq TO app_rt;
END IF; END $$;
