-- Connected timetable planning: rooms, teacher availability, subject quotas and
-- immutable publication snapshots. Existing timetable rows remain valid.

CREATE TABLE IF NOT EXISTS tenant_school.school_rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT NOT NULL REFERENCES tenant_school.schools(id) ON DELETE CASCADE,
    name        VARCHAR(120) NOT NULL,
    room_type   VARCHAR(48) NOT NULL DEFAULT 'CLASSROOM',
    capacity    INTEGER NOT NULL DEFAULT 0,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_school_room_name UNIQUE (school_id, name),
    CONSTRAINT chk_school_room_capacity CHECK (capacity >= 0)
);

ALTER TABLE tenant_school.school_class_subjects
    ADD COLUMN IF NOT EXISTS weekly_periods INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS preferred_part_of_day VARCHAR(16) NOT NULL DEFAULT 'ANY',
    ADD COLUMN IF NOT EXISTS required_room_type VARCHAR(48),
    ADD COLUMN IF NOT EXISTS double_period BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tenant_school.school_class_subjects
    DROP CONSTRAINT IF EXISTS chk_class_subject_weekly_periods,
    ADD CONSTRAINT chk_class_subject_weekly_periods CHECK (weekly_periods >= 0),
    DROP CONSTRAINT IF EXISTS chk_class_subject_part_of_day,
    ADD CONSTRAINT chk_class_subject_part_of_day CHECK (
        preferred_part_of_day IN ('ANY', 'MORNING', 'AFTERNOON')
    );

ALTER TABLE tenant_school.school_timetable_entries
    ADD COLUMN IF NOT EXISTS room_id BIGINT REFERENCES tenant_school.school_rooms(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tt_room_slot
    ON tenant_school.school_timetable_entries (school_id, academic_year_id, day_name, room_id);

CREATE TABLE IF NOT EXISTS tenant_school.school_teacher_availability (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id        BIGINT NOT NULL REFERENCES tenant_school.schools(id) ON DELETE CASCADE,
    academic_year_id VARCHAR(255) NOT NULL REFERENCES tenant_school.academic_years(id),
    teacher_id       BIGINT NOT NULL REFERENCES tenant_school.staff_members(id) ON DELETE CASCADE,
    day_name         VARCHAR(16) NOT NULL,
    bell_period_id   BIGINT NOT NULL REFERENCES tenant_school.school_bell_periods(id) ON DELETE CASCADE,
    available        BOOLEAN NOT NULL DEFAULT TRUE,
    note             VARCHAR(240),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_teacher_availability_slot UNIQUE (
        school_id, academic_year_id, teacher_id, day_name, bell_period_id
    ),
    CONSTRAINT chk_teacher_availability_day CHECK (
        day_name IN ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat')
    )
);

CREATE INDEX IF NOT EXISTS idx_teacher_availability_lookup
    ON tenant_school.school_teacher_availability
       (school_id, academic_year_id, teacher_id, day_name, bell_period_id);

CREATE TABLE IF NOT EXISTS tenant_school.school_timetable_publications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id        BIGINT NOT NULL REFERENCES tenant_school.schools(id) ON DELETE CASCADE,
    academic_year_id VARCHAR(255) NOT NULL REFERENCES tenant_school.academic_years(id),
    revision         INTEGER NOT NULL,
    label            VARCHAR(120) NOT NULL,
    snapshot         JSONB NOT NULL,
    published_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_by     BIGINT,
    CONSTRAINT uk_timetable_publication_revision UNIQUE (school_id, academic_year_id, revision),
    CONSTRAINT chk_timetable_publication_revision CHECK (revision > 0)
);

CREATE INDEX IF NOT EXISTS idx_timetable_publication_current
    ON tenant_school.school_timetable_publications
       (school_id, academic_year_id, revision DESC);

ALTER TABLE tenant_school.school_rooms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON tenant_school.school_rooms;
CREATE POLICY tenant_isolation ON tenant_school.school_rooms
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on');

ALTER TABLE tenant_school.school_teacher_availability ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON tenant_school.school_teacher_availability;
CREATE POLICY tenant_isolation ON tenant_school.school_teacher_availability
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on');

ALTER TABLE tenant_school.school_timetable_publications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON tenant_school.school_timetable_publications;
CREATE POLICY tenant_isolation ON tenant_school.school_timetable_publications
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint
              OR current_setting('app.bypass_rls', true) = 'on');

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app_rt') THEN
  GRANT SELECT, INSERT, UPDATE, DELETE ON
    tenant_school.school_rooms,
    tenant_school.school_teacher_availability,
    tenant_school.school_timetable_publications TO app_rt;
  GRANT USAGE, SELECT ON SEQUENCE
    tenant_school.school_rooms_id_seq,
    tenant_school.school_teacher_availability_id_seq,
    tenant_school.school_timetable_publications_id_seq TO app_rt;
END IF; END $$;
