CREATE TABLE IF NOT EXISTS tenant_school.school_timetable_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    school_id     BIGINT NOT NULL REFERENCES tenant_school.schools(id),
    day_name      VARCHAR(32) NOT NULL,
    period_label  VARCHAR(64) NOT NULL,
    class_section VARCHAR(128) NOT NULL,
    subject       VARCHAR(255),
    teacher       VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_school_timetable_school
    ON tenant_school.school_timetable_entries (school_id, created_at DESC);
