-- Timetable master data: bell schedules, periods, class->schedule map, per-class-per-year subjects.

CREATE TABLE tenant_school.school_bell_schedules (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id  BIGINT NOT NULL REFERENCES tenant_school.schools(id),
    name       VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_bell_sched_school_name UNIQUE (school_id, name)
);

CREATE TABLE tenant_school.school_bell_periods (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT NOT NULL REFERENCES tenant_school.schools(id),
    schedule_id BIGINT NOT NULL REFERENCES tenant_school.school_bell_schedules(id) ON DELETE CASCADE,
    sort_order  INTEGER NOT NULL,
    label       VARCHAR(64) NOT NULL,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,
    is_break    BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_bell_period_order UNIQUE (schedule_id, sort_order),
    CONSTRAINT ck_bell_period_time CHECK (end_time > start_time)
);
CREATE INDEX idx_bell_periods_sched ON tenant_school.school_bell_periods (schedule_id, sort_order);

CREATE TABLE tenant_school.school_class_bell_map (
    school_id   BIGINT NOT NULL REFERENCES tenant_school.schools(id),
    class_id    VARCHAR(255) NOT NULL REFERENCES tenant_school.school_classes(id),
    schedule_id BIGINT NOT NULL REFERENCES tenant_school.school_bell_schedules(id) ON DELETE CASCADE,
    PRIMARY KEY (school_id, class_id)
);

CREATE TABLE tenant_school.school_class_subjects (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id        BIGINT NOT NULL REFERENCES tenant_school.schools(id),
    class_id         VARCHAR(255) NOT NULL REFERENCES tenant_school.school_classes(id),
    academic_year_id VARCHAR(255) NOT NULL REFERENCES tenant_school.academic_years(id),
    subject_name     VARCHAR(120) NOT NULL,
    sort_order       INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_class_subject UNIQUE (school_id, class_id, academic_year_id, subject_name)
);
CREATE INDEX idx_class_subjects_lookup ON tenant_school.school_class_subjects (school_id, class_id, academic_year_id);

-- RLS (ENABLE not FORCE: Flyway owner/appuser bypasses; app_rt is subject).
ALTER TABLE tenant_school.school_bell_schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenant_school.school_bell_schedules
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on');
ALTER TABLE tenant_school.school_bell_periods ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenant_school.school_bell_periods
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on');
ALTER TABLE tenant_school.school_class_bell_map ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenant_school.school_class_bell_map
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on');
ALTER TABLE tenant_school.school_class_subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenant_school.school_class_subjects
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on');

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app_rt') THEN
  GRANT SELECT, INSERT, UPDATE, DELETE ON tenant_school.school_bell_schedules, tenant_school.school_bell_periods, tenant_school.school_class_bell_map, tenant_school.school_class_subjects TO app_rt;
  GRANT USAGE, SELECT ON SEQUENCE tenant_school.school_bell_schedules_id_seq, tenant_school.school_bell_periods_id_seq, tenant_school.school_class_subjects_id_seq TO app_rt;
END IF; END $$;
