-- Rework: the old school_timetable_entries was free-text and had no RLS. Drop and recreate
-- with FK-based, year-scoped columns. Forward-only; the few legacy free-text dev rows are
-- intentionally not migrated.
DROP TABLE IF EXISTS tenant_school.school_timetable_entries;

CREATE TABLE tenant_school.school_timetable_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id        BIGINT NOT NULL REFERENCES tenant_school.schools(id),
    academic_year_id VARCHAR(255) NOT NULL REFERENCES tenant_school.academic_years(id),
    section_id       VARCHAR(255) NOT NULL REFERENCES tenant_school.school_sections(id) ON DELETE CASCADE,
    day_name         VARCHAR(16) NOT NULL,
    bell_period_id   BIGINT NOT NULL REFERENCES tenant_school.school_bell_periods(id) ON DELETE CASCADE,
    subject_name     VARCHAR(120) NOT NULL,
    teacher_id       BIGINT REFERENCES tenant_school.staff_members(id) ON DELETE SET NULL,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_tt_slot UNIQUE (school_id, academic_year_id, section_id, day_name, bell_period_id)
);
CREATE INDEX idx_tt_section_year ON tenant_school.school_timetable_entries (school_id, academic_year_id, section_id);
CREATE INDEX idx_tt_teacher_slot ON tenant_school.school_timetable_entries (school_id, academic_year_id, day_name, bell_period_id, teacher_id);

ALTER TABLE tenant_school.school_timetable_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenant_school.school_timetable_entries
  USING      (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on')
  WITH CHECK (school_id = nullif(current_setting('app.current_school_id', true), '')::bigint OR current_setting('app.bypass_rls', true) = 'on');

DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app_rt') THEN
  GRANT SELECT, INSERT, UPDATE, DELETE ON tenant_school.school_timetable_entries TO app_rt;
  GRANT USAGE, SELECT ON SEQUENCE tenant_school.school_timetable_entries_id_seq TO app_rt;
END IF; END $$;
