#!/bin/sh
set -eu

: "${PORT:=80}"
: "${FRONTEND_UPSTREAM:=http://frontend:80}"
: "${NOTIFICATION_UPSTREAM:=http://notification-service:8080}"
: "${AUDIT_UPSTREAM:=http://audit-service:8080}"
: "${IDENTITY_UPSTREAM:=http://identity-service:8080}"
: "${TENANT_SCHOOL_UPSTREAM:=http://tenant-school-service:8080}"
: "${STUDENT_UPSTREAM:=http://student-service:8080}"
: "${ATTENDANCE_UPSTREAM:=http://attendance-service:8080}"
: "${FEE_UPSTREAM:=http://fee-service:8080}"
: "${CATALOG_UPSTREAM:=http://catalog-service:8080}"
: "${WORKFLOW_UPSTREAM:=http://workflow-service:8080}"
: "${FIREFIGHTING_UPSTREAM:=http://firefighting-service:8080}"
: "${REPORTING_UPSTREAM:=http://reporting-service:8080}"
: "${BILLING_UPSTREAM:=http://billing-service:8080}"
require_token() {
  name="$1"
  value="$(eval "printf '%s' \"\${$name:-}\"")"
  if [ -z "$value" ] || [ "$value" = "unused" ]; then
    echo "Missing required gateway service token: $name" >&2
    exit 1
  fi
}

require_token NOTIFICATION_SERVICE_TOKEN
require_token AUDIT_SERVICE_TOKEN
require_token IDENTITY_SERVICE_TOKEN
require_token TENANT_SCHOOL_SERVICE_TOKEN
require_token STUDENT_SERVICE_TOKEN
require_token ATTENDANCE_SERVICE_TOKEN
require_token FEE_SERVICE_TOKEN
require_token CATALOG_SERVICE_TOKEN
require_token WORKFLOW_SERVICE_TOKEN
require_token FIREFIGHTING_SERVICE_TOKEN
require_token REPORTING_SERVICE_TOKEN
require_token BILLING_SERVICE_TOKEN

export PORT FRONTEND_UPSTREAM NOTIFICATION_UPSTREAM AUDIT_UPSTREAM IDENTITY_UPSTREAM
export TENANT_SCHOOL_UPSTREAM STUDENT_UPSTREAM ATTENDANCE_UPSTREAM FEE_UPSTREAM CATALOG_UPSTREAM
export WORKFLOW_UPSTREAM FIREFIGHTING_UPSTREAM REPORTING_UPSTREAM BILLING_UPSTREAM
export NOTIFICATION_SERVICE_TOKEN AUDIT_SERVICE_TOKEN IDENTITY_SERVICE_TOKEN TENANT_SCHOOL_SERVICE_TOKEN
export STUDENT_SERVICE_TOKEN ATTENDANCE_SERVICE_TOKEN FEE_SERVICE_TOKEN CATALOG_SERVICE_TOKEN
export WORKFLOW_SERVICE_TOKEN FIREFIGHTING_SERVICE_TOKEN REPORTING_SERVICE_TOKEN BILLING_SERVICE_TOKEN

envsubst '${PORT} ${FRONTEND_UPSTREAM} ${NOTIFICATION_UPSTREAM} ${AUDIT_UPSTREAM} ${IDENTITY_UPSTREAM} ${TENANT_SCHOOL_UPSTREAM} ${STUDENT_UPSTREAM} ${ATTENDANCE_UPSTREAM} ${FEE_UPSTREAM} ${CATALOG_UPSTREAM} ${WORKFLOW_UPSTREAM} ${FIREFIGHTING_UPSTREAM} ${REPORTING_UPSTREAM} ${BILLING_UPSTREAM} ${NOTIFICATION_SERVICE_TOKEN} ${AUDIT_SERVICE_TOKEN} ${IDENTITY_SERVICE_TOKEN} ${TENANT_SCHOOL_SERVICE_TOKEN} ${STUDENT_SERVICE_TOKEN} ${ATTENDANCE_SERVICE_TOKEN} ${FEE_SERVICE_TOKEN} ${CATALOG_SERVICE_TOKEN} ${WORKFLOW_SERVICE_TOKEN} ${FIREFIGHTING_SERVICE_TOKEN} ${REPORTING_SERVICE_TOKEN} ${BILLING_SERVICE_TOKEN}' \
  < /etc/nginx/gateway/default.conf.template \
  > /etc/nginx/conf.d/default.conf
