import sys
if __name__ == '__main__' and '--apply-dev' not in sys.argv:
 raise SystemExit('Explicit --apply-dev is required; this tool targets isolated custoking-dev synthetic acceptance only')
import json,pathlib,secrets,runpy
ROOT=pathlib.Path(__file__).resolve().parents[2]/'tmp';cloud=runpy.run_path(str(pathlib.Path(__file__).resolve().with_name('provision-security-acceptance.py')))['cloud'];manifest=json.loads((ROOT/'security-acceptance-fixture-job.json').read_text());job='ims-dev-security-fixture-disable-'+secrets.token_hex(8);manifest['metadata']['name']=job
sql="BEGIN; SET LOCAL statement_timeout='15s'; DO $$ BEGIN IF (SELECT count(*) FROM identity.app_users WHERE id IN(990007203,990007204) AND full_name LIKE 'SEC-ACPT-20261007-RECOVERY-%' AND email LIKE 'sec-acpt-20261007-recovery-%@security-fixture.invalid')<>2 THEN RAISE EXCEPTION 'Exact synthetic recovery actor ownership mismatch'; END IF; END $$; UPDATE identity.app_users SET deleted_at=now(),deleted_by='SEC-ACPT-20261007-OWNER-CLEANUP',credential_version=credential_version+1 WHERE id IN(990007203,990007204); UPDATE identity.auth_sessions SET status='REVOKED' WHERE user_id IN(990007203,990007204); UPDATE identity.user_role_assignments SET active=false,revoked_at=now() WHERE user_id IN(990007203,990007204); DELETE FROM identity.passkey_credentials WHERE user_id IN(990007203,990007204); DELETE FROM identity.session_step_up WHERE user_id IN(990007203,990007204); DELETE FROM identity.passkey_challenges WHERE user_id IN(990007203,990007204); INSERT INTO identity.rbac_audit_log(event_type,target_user_id,new_value,correlation_id) SELECT 'SYNTHETIC_RECOVERY_ACTOR_DISABLED',id,'Marker-bound owner acceptance cleanup; every session revoked','SEC-ACPT-20261007' FROM identity.app_users WHERE id IN(990007203,990007204); COMMIT;"
manifest['spec']['template']['spec']['template']['spec']['containers'][0]['args']=['-X','-A','-t','-v','ON_ERROR_STOP=1','-c',sql];path=ROOT/'security-acceptance-disable-job.json';path.write_text(json.dumps(manifest))
try:
 cloud(['run','jobs','replace',str(path),'--region=asia-south2','--quiet','--format=json']);result=cloud(['run','jobs','execute',job,'--region=asia-south2','--wait','--quiet','--format=json'])
 if not any(c.get('type')=='Completed'and c.get('status')=='True'for c in result.get('status',{}).get('conditions',[])):raise RuntimeError('Synthetic privileged actor cleanup failed')
 print('Two exact reserved recovery actors disabled; sessions/assignments/factors revoked, audit retained')
finally:cloud(['run','jobs','delete',job,'--region=asia-south2','--quiet','--format=json'])
