-- =============================================================
-- V99 – BCrypt password migration placeholder
-- =============================================================
-- This migration is a no-op. It marks the point at which the
-- application switched from SHA-256 to BCrypt (cost 12) for
-- password hashing.
--
-- Existing rows in app_users.password_hash contain SHA-256
-- hashes that are now INVALID. On first boot after this
-- migration, DatabaseBootstrap will create seed users with
-- BCrypt hashes if they do not already exist.
--
-- OPERATOR ACTION REQUIRED before first boot:
--   DELETE FROM app_users WHERE true;
-- OR reset individual passwords via the admin panel.
--
-- DO NOT DROP OR ALTER the password_hash column; it is already
-- VARCHAR and accepts BCrypt hashes without schema changes.
-- =============================================================
SELECT 1;
