CREATE TABLE IF NOT EXISTS billing_customers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code         VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    email        VARCHAR(255),
    phone        VARCHAR(255),
    gstin        VARCHAR(255),
    address_line TEXT,
    branch_id    BIGINT       NOT NULL,
    branch_name  VARCHAR(255) NOT NULL,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS billing_invoices (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invoice_no        VARCHAR(255) NOT NULL,
    customer_id       BIGINT       NOT NULL REFERENCES billing_customers(id),
    branch_id         BIGINT       NOT NULL,
    branch_name       VARCHAR(255) NOT NULL,
    invoice_date      DATE         NOT NULL,
    due_date          DATE         NOT NULL,
    subtotal          BIGINT       NOT NULL,
    discount_percent  NUMERIC(8, 2) NOT NULL DEFAULT 0,
    discount_amount   BIGINT       NOT NULL,
    tax_amount        BIGINT       NOT NULL,
    grand_total       BIGINT       NOT NULL,
    paid_amount       BIGINT       NOT NULL DEFAULT 0,
    balance_amount    BIGINT       NOT NULL,
    status            VARCHAR(255) NOT NULL,
    payment_status    VARCHAR(255) NOT NULL,
    approval_status   VARCHAR(255) NOT NULL,
    notes             TEXT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (invoice_no)
);

CREATE TABLE IF NOT EXISTS billing_invoice_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invoice_id  BIGINT       NOT NULL REFERENCES billing_invoices(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    quantity    BIGINT       NOT NULL,
    unit_price  BIGINT       NOT NULL,
    tax_rate    NUMERIC(8, 2) NOT NULL DEFAULT 0,
    line_total  BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS billing_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invoice_id    BIGINT       NOT NULL REFERENCES billing_invoices(id),
    branch_id     BIGINT       NOT NULL,
    branch_name   VARCHAR(255) NOT NULL,
    payment_date  DATE         NOT NULL,
    amount        BIGINT       NOT NULL,
    payment_mode  VARCHAR(255) NOT NULL,
    reference_no  VARCHAR(255),
    notes         TEXT,
    received_by   VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

