INSERT INTO identity.roles (name, description, created_at)
VALUES
    ('SUPERADMIN', 'Full platform administration', now()),
    ('ZONE_ADMIN', 'Zone-level school oversight', now()),
    ('ADMIN', 'School administrator', now()),
    ('SCHOOL_ADMIN', 'School administrator', now()),
    ('OPERATIONS', 'School operations user', now()),
    ('ACCOUNTANT', 'School finance user', now()),
    ('TEACHER', 'Classroom teacher', now()),
    ('VIEWER', 'Read-only school user', now())
ON CONFLICT (name) DO NOTHING;

INSERT INTO identity.permissions (code, description, created_at)
VALUES
    ('platform:admin', 'Administer the platform', now()),
    ('workspace:access', 'Access the workspace', now()),
    ('school:read', 'Read school records and setup', now()),
    ('school:create', 'Create schools', now()),
    ('school:update', 'Update school records and setup', now()),
    ('school:admin_manage', 'Manage school administrators', now()),
    ('school:suspend', 'Suspend schools', now()),
    ('zone:read', 'Read zones', now()),
    ('zone:manage', 'Manage zones', now()),
    ('zone:assign_school', 'Assign schools and admins to zones', now()),
    ('student:read', 'Read student records', now()),
    ('student:create', 'Create students', now()),
    ('student:update', 'Update students', now()),
    ('student:delete', 'Delete students', now()),
    ('student:import', 'Bulk import students', now()),
    ('attendance:read', 'Read attendance', now()),
    ('attendance:manage', 'Manage attendance', now()),
    ('fee:read', 'Read fees', now()),
    ('fee:collect', 'Collect fees', now()),
    ('fee:reverse', 'Reverse fee payments', now()),
    ('fee:assign', 'Assign fees', now()),
    ('fee_structure:read', 'Read fee structure', now()),
    ('fee_structure:manage', 'Manage fee structure', now()),
    ('order:read', 'Read catalog orders', now()),
    ('order:create', 'Create catalog orders', now()),
    ('order:update', 'Update catalog orders', now()),
    ('order:approve', 'Approve catalog orders', now()),
    ('order:fulfill', 'Fulfill catalog orders', now()),
    ('order:reject', 'Reject catalog orders', now()),
    ('firefighting:read', 'Read urgent procurement requests', now()),
    ('firefighting:create', 'Create urgent procurement requests', now()),
    ('firefighting:update', 'Update urgent procurement requests', now()),
    ('firefighting:approve', 'Approve urgent procurement requests', now()),
    ('firefighting:fulfill', 'Fulfill urgent procurement requests', now()),
    ('payment:read', 'Read payments', now()),
    ('payment:create', 'Create payments', now()),
    ('payment:reconcile', 'Reconcile payments', now()),
    ('invoice:read', 'Read invoices', now()),
    ('invoice:create', 'Create invoices', now()),
    ('invoice:cancel', 'Cancel invoices', now()),
    ('customer:read', 'Read customers', now()),
    ('customer:create', 'Create customers', now()),
    ('report:read', 'Read reports', now()),
    ('audit:read', 'Read audit logs', now()),
    ('user:manage', 'Manage users', now()),
    ('user:read', 'Read users', now()),
    ('user:create', 'Create users', now()),
    ('user:update', 'Update users', now()),
    ('user:disable', 'Disable users', now()),
    ('user:reset_password', 'Reset user passwords', now()),
    ('timetable:read', 'Read timetables', now()),
    ('timetable:manage', 'Manage timetables', now()),
    ('staff:read', 'Read staff records', now()),
    ('staff:manage', 'Manage staff records', now()),
    ('plan:read', 'Read annual plans', now()),
    ('plan:manage', 'Manage annual plans', now()),
    ('workflow:read', 'Read workflow state', now()),
    ('workflow:act', 'Act on workflow tasks', now()),
    ('role:read', 'Read RBAC roles', now()),
    ('role:create', 'Create RBAC roles', now()),
    ('role:update', 'Update RBAC roles', now()),
    ('role:assign', 'Assign RBAC roles', now()),
    ('role:revoke', 'Revoke RBAC roles', now()),
    ('role:disable', 'Disable RBAC roles', now()),
    ('permission:read', 'Read RBAC permissions', now()),
    ('permission:assign', 'Assign RBAC permissions', now()),
    ('permission:revoke', 'Revoke RBAC permissions', now()),
    ('notification:read', 'Read notification records', now()),
    ('notification:send', 'Send notifications', now()),
    ('system:actuator', 'Read system actuator endpoints', now())
ON CONFLICT (code) DO UPDATE SET description = EXCLUDED.description;

WITH default_grants(role_name, permission_code) AS (
    VALUES
        ('SUPERADMIN', 'platform:admin'),
        ('SUPERADMIN', 'workspace:access'),
        ('SUPERADMIN', 'school:read'),
        ('SUPERADMIN', 'school:create'),
        ('SUPERADMIN', 'school:update'),
        ('SUPERADMIN', 'school:admin_manage'),
        ('SUPERADMIN', 'school:suspend'),
        ('SUPERADMIN', 'zone:read'),
        ('SUPERADMIN', 'zone:manage'),
        ('SUPERADMIN', 'zone:assign_school'),
        ('SUPERADMIN', 'student:read'),
        ('SUPERADMIN', 'student:create'),
        ('SUPERADMIN', 'student:update'),
        ('SUPERADMIN', 'student:delete'),
        ('SUPERADMIN', 'student:import'),
        ('SUPERADMIN', 'attendance:read'),
        ('SUPERADMIN', 'attendance:manage'),
        ('SUPERADMIN', 'fee:read'),
        ('SUPERADMIN', 'fee:collect'),
        ('SUPERADMIN', 'fee:reverse'),
        ('SUPERADMIN', 'fee:assign'),
        ('SUPERADMIN', 'fee_structure:read'),
        ('SUPERADMIN', 'fee_structure:manage'),
        ('SUPERADMIN', 'order:read'),
        ('SUPERADMIN', 'order:create'),
        ('SUPERADMIN', 'order:update'),
        ('SUPERADMIN', 'order:approve'),
        ('SUPERADMIN', 'order:fulfill'),
        ('SUPERADMIN', 'order:reject'),
        ('SUPERADMIN', 'firefighting:read'),
        ('SUPERADMIN', 'firefighting:create'),
        ('SUPERADMIN', 'firefighting:update'),
        ('SUPERADMIN', 'firefighting:approve'),
        ('SUPERADMIN', 'firefighting:fulfill'),
        ('SUPERADMIN', 'payment:read'),
        ('SUPERADMIN', 'payment:create'),
        ('SUPERADMIN', 'payment:reconcile'),
        ('SUPERADMIN', 'invoice:read'),
        ('SUPERADMIN', 'invoice:create'),
        ('SUPERADMIN', 'invoice:cancel'),
        ('SUPERADMIN', 'customer:read'),
        ('SUPERADMIN', 'customer:create'),
        ('SUPERADMIN', 'report:read'),
        ('SUPERADMIN', 'audit:read'),
        ('SUPERADMIN', 'user:manage'),
        ('SUPERADMIN', 'user:read'),
        ('SUPERADMIN', 'user:create'),
        ('SUPERADMIN', 'user:update'),
        ('SUPERADMIN', 'user:disable'),
        ('SUPERADMIN', 'user:reset_password'),
        ('SUPERADMIN', 'timetable:read'),
        ('SUPERADMIN', 'timetable:manage'),
        ('SUPERADMIN', 'staff:read'),
        ('SUPERADMIN', 'staff:manage'),
        ('SUPERADMIN', 'plan:read'),
        ('SUPERADMIN', 'plan:manage'),
        ('SUPERADMIN', 'workflow:read'),
        ('SUPERADMIN', 'workflow:act'),
        ('SUPERADMIN', 'role:read'),
        ('SUPERADMIN', 'role:create'),
        ('SUPERADMIN', 'role:update'),
        ('SUPERADMIN', 'role:assign'),
        ('SUPERADMIN', 'role:revoke'),
        ('SUPERADMIN', 'role:disable'),
        ('SUPERADMIN', 'permission:read'),
        ('SUPERADMIN', 'permission:assign'),
        ('SUPERADMIN', 'permission:revoke'),
        ('SUPERADMIN', 'notification:read'),
        ('SUPERADMIN', 'notification:send'),
        ('SUPERADMIN', 'system:actuator'),

        ('ZONE_ADMIN', 'workspace:access'),
        ('ZONE_ADMIN', 'school:read'),
        ('ZONE_ADMIN', 'zone:read'),
        ('ZONE_ADMIN', 'zone:manage'),
        ('ZONE_ADMIN', 'zone:assign_school'),
        ('ZONE_ADMIN', 'report:read'),
        ('ZONE_ADMIN', 'audit:read'),

        ('ADMIN', 'workspace:access'),
        ('ADMIN', 'school:read'),
        ('ADMIN', 'school:update'),
        ('ADMIN', 'student:read'),
        ('ADMIN', 'student:create'),
        ('ADMIN', 'student:update'),
        ('ADMIN', 'student:delete'),
        ('ADMIN', 'student:import'),
        ('ADMIN', 'attendance:read'),
        ('ADMIN', 'attendance:manage'),
        ('ADMIN', 'fee:read'),
        ('ADMIN', 'fee:collect'),
        ('ADMIN', 'fee:reverse'),
        ('ADMIN', 'fee:assign'),
        ('ADMIN', 'fee_structure:read'),
        ('ADMIN', 'fee_structure:manage'),
        ('ADMIN', 'order:read'),
        ('ADMIN', 'order:create'),
        ('ADMIN', 'order:update'),
        ('ADMIN', 'order:approve'),
        ('ADMIN', 'order:reject'),
        ('ADMIN', 'firefighting:read'),
        ('ADMIN', 'firefighting:create'),
        ('ADMIN', 'firefighting:update'),
        ('ADMIN', 'firefighting:approve'),
        ('ADMIN', 'payment:read'),
        ('ADMIN', 'payment:create'),
        ('ADMIN', 'invoice:read'),
        ('ADMIN', 'invoice:create'),
        ('ADMIN', 'report:read'),
        ('ADMIN', 'notification:read'),
        ('ADMIN', 'notification:send'),
        ('ADMIN', 'timetable:read'),
        ('ADMIN', 'timetable:manage'),
        ('ADMIN', 'staff:read'),
        ('ADMIN', 'staff:manage'),
        ('ADMIN', 'plan:read'),
        ('ADMIN', 'plan:manage'),
        ('ADMIN', 'workflow:read'),
        ('ADMIN', 'workflow:act'),

        ('SCHOOL_ADMIN', 'workspace:access'),
        ('SCHOOL_ADMIN', 'school:read'),
        ('SCHOOL_ADMIN', 'school:update'),
        ('SCHOOL_ADMIN', 'student:read'),
        ('SCHOOL_ADMIN', 'student:create'),
        ('SCHOOL_ADMIN', 'student:update'),
        ('SCHOOL_ADMIN', 'student:delete'),
        ('SCHOOL_ADMIN', 'student:import'),
        ('SCHOOL_ADMIN', 'attendance:read'),
        ('SCHOOL_ADMIN', 'attendance:manage'),
        ('SCHOOL_ADMIN', 'fee:read'),
        ('SCHOOL_ADMIN', 'fee:collect'),
        ('SCHOOL_ADMIN', 'fee:reverse'),
        ('SCHOOL_ADMIN', 'fee:assign'),
        ('SCHOOL_ADMIN', 'fee_structure:read'),
        ('SCHOOL_ADMIN', 'fee_structure:manage'),
        ('SCHOOL_ADMIN', 'order:read'),
        ('SCHOOL_ADMIN', 'order:create'),
        ('SCHOOL_ADMIN', 'order:update'),
        ('SCHOOL_ADMIN', 'order:approve'),
        ('SCHOOL_ADMIN', 'order:reject'),
        ('SCHOOL_ADMIN', 'firefighting:read'),
        ('SCHOOL_ADMIN', 'firefighting:create'),
        ('SCHOOL_ADMIN', 'firefighting:update'),
        ('SCHOOL_ADMIN', 'firefighting:approve'),
        ('SCHOOL_ADMIN', 'payment:read'),
        ('SCHOOL_ADMIN', 'payment:create'),
        ('SCHOOL_ADMIN', 'invoice:read'),
        ('SCHOOL_ADMIN', 'invoice:create'),
        ('SCHOOL_ADMIN', 'report:read'),
        ('SCHOOL_ADMIN', 'notification:read'),
        ('SCHOOL_ADMIN', 'notification:send'),
        ('SCHOOL_ADMIN', 'timetable:read'),
        ('SCHOOL_ADMIN', 'timetable:manage'),
        ('SCHOOL_ADMIN', 'staff:read'),
        ('SCHOOL_ADMIN', 'staff:manage'),
        ('SCHOOL_ADMIN', 'plan:read'),
        ('SCHOOL_ADMIN', 'plan:manage'),
        ('SCHOOL_ADMIN', 'workflow:read'),
        ('SCHOOL_ADMIN', 'workflow:act'),

        ('OPERATIONS', 'workspace:access'),
        ('OPERATIONS', 'student:read'),
        ('OPERATIONS', 'student:create'),
        ('OPERATIONS', 'student:update'),
        ('OPERATIONS', 'attendance:read'),
        ('OPERATIONS', 'attendance:manage'),
        ('OPERATIONS', 'order:read'),
        ('OPERATIONS', 'order:create'),
        ('OPERATIONS', 'order:update'),
        ('OPERATIONS', 'firefighting:read'),
        ('OPERATIONS', 'firefighting:create'),
        ('OPERATIONS', 'firefighting:update'),
        ('OPERATIONS', 'timetable:read'),
        ('OPERATIONS', 'workflow:read'),

        ('ACCOUNTANT', 'workspace:access'),
        ('ACCOUNTANT', 'fee:read'),
        ('ACCOUNTANT', 'fee:collect'),
        ('ACCOUNTANT', 'fee:reverse'),
        ('ACCOUNTANT', 'fee:assign'),
        ('ACCOUNTANT', 'fee_structure:read'),
        ('ACCOUNTANT', 'fee_structure:manage'),
        ('ACCOUNTANT', 'payment:read'),
        ('ACCOUNTANT', 'payment:create'),
        ('ACCOUNTANT', 'payment:reconcile'),
        ('ACCOUNTANT', 'invoice:read'),
        ('ACCOUNTANT', 'invoice:create'),
        ('ACCOUNTANT', 'invoice:cancel'),
        ('ACCOUNTANT', 'order:read'),

        ('TEACHER', 'workspace:access'),
        ('TEACHER', 'student:read'),
        ('TEACHER', 'attendance:read'),
        ('TEACHER', 'attendance:manage'),
        ('TEACHER', 'timetable:read'),

        ('VIEWER', 'workspace:access'),
        ('VIEWER', 'student:read'),
        ('VIEWER', 'attendance:read'),
        ('VIEWER', 'fee:read'),
        ('VIEWER', 'payment:read'),
        ('VIEWER', 'order:read'),
        ('VIEWER', 'plan:read'),
        ('VIEWER', 'timetable:read')
)
INSERT INTO identity.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM default_grants g
JOIN identity.roles r ON r.name = g.role_name
JOIN identity.permissions p ON p.code = g.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;
