param(
    [string]$RuntimeRoot = "D:\Projects\Runtime",
    [string]$IdeaProduct = "IntelliJIdea2026.1",
    [switch]$MigrateIntelliJ,
    [switch]$MoveDockerDisk,
    [switch]$MoveDockerWslMain
)

$ErrorActionPreference = "Stop"

function New-Directory {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Convert-ToIdeaPath {
    param([string]$Path)

    return ($Path -replace "\\", "/")
}

function Test-ProcessRunning {
    param([string[]]$Names)

    foreach ($name in $Names) {
        if (Get-Process -Name $name -ErrorAction SilentlyContinue) {
            return $true
        }
    }
    return $false
}

function Invoke-Robocopy {
    param(
        [string]$Source,
        [string]$Destination,
        [string[]]$ExtraArgs = @()
    )

    if (-not (Test-Path -LiteralPath $Source)) {
        Write-Host "Skip missing source: $Source"
        return
    }

    New-Directory $Destination
    & robocopy $Source $Destination /E /R:2 /W:2 @ExtraArgs
    if ($LASTEXITCODE -gt 7) {
        throw "robocopy failed from '$Source' to '$Destination' with exit code $LASTEXITCODE"
    }
}

function Invoke-External {
    param(
        [string]$FilePath,
        [string[]]$Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "'$FilePath $($Arguments -join ' ')' failed with exit code $LASTEXITCODE"
    }
}

function Stop-DockerDesktop {
    $dockerCli = "C:\Program Files\Docker\Docker\DockerCli.exe"
    if (Test-Path -LiteralPath $dockerCli) {
        & $dockerCli -Shutdown | Out-Null
    }

    $deadline = (Get-Date).AddSeconds(60)
    do {
        $running = Get-Process -ErrorAction SilentlyContinue |
            Where-Object {
                $_.ProcessName -in @(
                    "Docker Desktop",
                    "com.docker.backend",
                    "com.docker.build",
                    "docker-agent",
                    "docker-sandbox"
                )
            }

        if (-not $running) {
            break
        }

        Start-Sleep -Seconds 2
    } while ((Get-Date) -lt $deadline)

    $stillRunning = Get-Process -ErrorAction SilentlyContinue |
        Where-Object {
            $_.ProcessName -in @(
                "Docker Desktop",
                "com.docker.backend",
                "com.docker.build",
                "docker-agent",
                "docker-sandbox"
            )
        }

    if ($stillRunning) {
        $names = ($stillRunning | Select-Object -ExpandProperty ProcessName -Unique) -join ", "
        throw "Docker Desktop is still running. Close it from the tray and rerun this script. Running: $names"
    }

    Invoke-External -FilePath "wsl" -Arguments @("--shutdown")
}

function Assert-WithinPath {
    param(
        [string]$Path,
        [string]$ExpectedRoot
    )

    $resolvedPath = [System.IO.Path]::GetFullPath($Path)
    $resolvedRoot = [System.IO.Path]::GetFullPath($ExpectedRoot)

    if (-not $resolvedPath.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to operate on '$resolvedPath' because it is outside '$resolvedRoot'"
    }
}

$runtimeRootFull = [System.IO.Path]::GetFullPath($RuntimeRoot)
$jetBrainsRoot = Join-Path $runtimeRootFull "JetBrains\$IdeaProduct"
$ideaConfig = Join-Path $jetBrainsRoot "config"
$ideaSystem = Join-Path $jetBrainsRoot "system"
$ideaPlugins = Join-Path $jetBrainsRoot "plugins"
$ideaLog = Join-Path $jetBrainsRoot "log"
$ideaProperties = Join-Path $jetBrainsRoot "idea.properties"
$dockerRuntimeRoot = Join-Path $runtimeRootFull "Docker"
$wslRuntimeRoot = Join-Path $runtimeRootFull "WSL"

New-Directory $runtimeRootFull
New-Directory $dockerRuntimeRoot
New-Directory $wslRuntimeRoot
New-Directory $jetBrainsRoot
New-Directory $ideaConfig
New-Directory $ideaSystem
New-Directory $ideaPlugins
New-Directory $ideaLog

$ideaPropertiesContent = @(
    "# Generated by scripts/configure-windows-runtime.ps1.",
    "# Restart IntelliJ IDEA after changing this file.",
    "idea.config.path=$(Convert-ToIdeaPath $ideaConfig)",
    "idea.system.path=$(Convert-ToIdeaPath $ideaSystem)",
    "idea.plugins.path=$(Convert-ToIdeaPath $ideaPlugins)",
    "idea.log.path=$(Convert-ToIdeaPath $ideaLog)"
)

Set-Content -Path $ideaProperties -Value $ideaPropertiesContent -Encoding ASCII
[Environment]::SetEnvironmentVariable("IDEA_PROPERTIES", $ideaProperties, "User")
$env:IDEA_PROPERTIES = $ideaProperties

Write-Host "Runtime root: $runtimeRootFull"
Write-Host "Configured IDEA_PROPERTIES for future IntelliJ launches:"
Write-Host "  $ideaProperties"

if ($MigrateIntelliJ) {
    if (Test-ProcessRunning -Names @("idea64", "idea")) {
        throw "Close IntelliJ IDEA before running with -MigrateIntelliJ."
    }

    $sourceConfig = Join-Path $env:APPDATA "JetBrains\$IdeaProduct"
    $sourceSystem = Join-Path $env:LOCALAPPDATA "JetBrains\$IdeaProduct"
    $sourcePlugins = Join-Path $sourceConfig "plugins"
    $sourceLog = Join-Path $sourceSystem "log"

    Invoke-Robocopy -Source $sourceConfig -Destination $ideaConfig -ExtraArgs @("/XD", "plugins", "/XF", ".lock")
    Invoke-Robocopy -Source $sourcePlugins -Destination $ideaPlugins
    Invoke-Robocopy -Source $sourceSystem -Destination $ideaSystem -ExtraArgs @("/XD", "log", "plugins", "/XF", ".lock")
    Invoke-Robocopy -Source $sourceLog -Destination $ideaLog
}

if ($MoveDockerDisk) {
    Stop-DockerDesktop

    $sourceDisk = Join-Path $env:LOCALAPPDATA "Docker\wsl\disk"
    $targetDisk = Join-Path $dockerRuntimeRoot "wsl\disk"
    $sourceRoot = Join-Path $env:LOCALAPPDATA "Docker\wsl"

    Assert-WithinPath -Path $sourceDisk -ExpectedRoot $sourceRoot
    Assert-WithinPath -Path $targetDisk -ExpectedRoot $dockerRuntimeRoot

    if (Test-Path -LiteralPath $sourceDisk) {
        $sourceItem = Get-Item -LiteralPath $sourceDisk -Force
        if (($sourceItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            Write-Host "Docker disk path is already redirected: $sourceDisk"
        } else {
            if ((Test-Path -LiteralPath $targetDisk) -and ((Get-ChildItem -LiteralPath $targetDisk -Force | Select-Object -First 1))) {
                throw "Target Docker disk directory is not empty: $targetDisk"
            }

            New-Directory (Split-Path -Parent $targetDisk)
            if (Test-Path -LiteralPath $targetDisk) {
                Remove-Item -LiteralPath $targetDisk -Force
            }

            Move-Item -LiteralPath $sourceDisk -Destination (Split-Path -Parent $targetDisk)
            New-Item -ItemType Junction -Path $sourceDisk -Target $targetDisk | Out-Null
            Write-Host "Moved Docker WSL data disk to $targetDisk and left a junction at $sourceDisk"
        }
    } else {
        Write-Host "Docker disk source does not exist yet: $sourceDisk"
    }
}

if ($MoveDockerWslMain) {
    Write-Warning "Skipping docker-desktop WSL main distro move. Docker Desktop manages this small distro and may recreate it under LOCALAPPDATA at startup. Use -MoveDockerDisk for the large Docker data disk."
}

Write-Host "Done."
