GRANT USAGE ON SCHEMA catalog TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA catalog TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA catalog TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA tenant_school TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA tenant_school TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA tenant_school TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_school GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_school GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
