GRANT USAGE ON SCHEMA
  notification,
  audit,
  identity,
  tenant_school,
  student,
  attendance,
  fee,
  catalog,
  workflow,
  firefighting,
  reporting,
  billing
TO ims_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA
  notification,
  audit,
  identity,
  tenant_school,
  student,
  attendance,
  fee,
  catalog,
  workflow,
  firefighting,
  reporting,
  billing
TO ims_app;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA
  notification,
  audit,
  identity,
  tenant_school,
  student,
  attendance,
  fee,
  catalog,
  workflow,
  firefighting,
  reporting,
  billing
TO ims_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_school GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA student GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA attendance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fee GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA workflow GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA firefighting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_school GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA student GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA attendance GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fee GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA workflow GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA firefighting GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
