GRANT USAGE ON SCHEMA audit TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA audit TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA notification TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA notification TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA notification TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA student TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA student TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA student TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA student GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA student GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA attendance TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA attendance TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA attendance TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA attendance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA attendance GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA fee TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fee TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA fee TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fee GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fee GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA workflow TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA workflow TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA workflow TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA workflow GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA workflow GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA firefighting TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA firefighting TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA firefighting TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA firefighting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA firefighting GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA reporting TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA reporting TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA reporting TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;

GRANT USAGE ON SCHEMA billing TO ims_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA billing TO ims_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA billing TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ims_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ims_app;
